### ISSUE TITLE
HUD display within CollectionViewCell?

### ISSUE THREAD

**Issue by rmickeyd** [pkluz/PKHUD#84] opened 2016-04-11 06:10 UTC
Is it possible to have it not display over whole screen just in collectionViewCell?

**Comment by pkluz** [comment] 2016-04-11 09:18
I'm planning on adding a feature to display the HUD within any `UIView` type, so yes this will be possible soon. Not sure how it's going to look like within small elements like cells, but that's up to you to customize. Duplicate of #79

**Closed** 2016-04-11 09:19 UTC
Labels: duplicate
