### ISSUE TITLE
 Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by mohkin** [pkluz/PKHUD#118] opened 2016-10-31 09:57 UTC
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: /Users/mac/Library/Developer/Xcode/DerivedData/Project/Build/Products/Debug-iphoneos/PKHUD.framework/Modules/PKHUD.swiftmodule/arm64.swiftmodule

Pod File:

```
use_frameworks!

target 'Project' do
    pod 'Alamofire', '4.0'
 pod 'Kingfisher', '~> 3.0'
 pod "CZPicker"
 pod 'DKImagePickerController'
 pod 'PKHUD', '~> 4.0'
 pod 'FacebookLogin'
 pod 'DatePickerDialog'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0.1'
        end
    end
  end

```
Update: The application works fine on IOS 10.1 Simulator , But doesnt work on the IOS 10.1 phone

**Comment by PGLongo** [comment] 2016-11-01 12:29
I think that if you have to set the build_settings to 3.0.1 you have to rebuild yourself PKHUD after adding it with CocoaPods. 

Try to select PKHUD in **Manage Schemes** and then rebuild it

**Comment by PGLongo** [comment] 2016-11-04 11:30
@mohkin any news?

**Comment by PGLongo** [comment] 2016-12-20 13:20
I cannot reproduce this error. I close this issue for the moment

**Closed by PGLongo** 2016-12-20 13:20 UTC
